name: Handle Request
on:
  issues:
    types: [opened]
jobs:
  my-action:
    runs-on: ubuntu-latest
    steps:
      # Check out code using git
      - uses: actions/checkout@v2
      # Install Node 12
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: egordm/gha-yarn-node-cache@v1
      - uses: Jaid/action-npm-install@v1.2.4
      # Node.js script can be anywhere. A good convention is to put local GitHub Actions
      # into the `.github/actions` folder
      - name: "Handle issue"
        run: node ./action/index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
